// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_login from "./routes/api/login.ts";
import * as $api_register from "./routes/api/register.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $menu from "./routes/menu.tsx";
import * as $register from "./routes/register.tsx";
import * as $loginForm from "./islands/loginForm.tsx";
import * as $registerForm from "./islands/registerForm.tsx";
import * as $studentMenu from "./islands/studentMenu.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/login.ts": $api_login,
    "./routes/api/register.ts": $api_register,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/menu.tsx": $menu,
    "./routes/register.tsx": $register,
  },
  islands: {
    "./islands/loginForm.tsx": $loginForm,
    "./islands/registerForm.tsx": $registerForm,
    "./islands/studentMenu.tsx": $studentMenu,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
